<?php
$_tokens = array (
  'account_changepassword_failure' => 'Kennwort wurde nicht geändert',
  'account_changepassword_nav' => 'Kennwort',
  'account_changepassword_success' => 'Kennwort ist geändert',
  'account_edit_failure' => 'Benutzerkonto ist nicht geändert',
  'account_edit_success' => 'Benutzerkonto ist geändert',
  'account_h1' => 'Benutzerkonto',
  'account_head_title' => 'Benutzerkonto',
  'account_index_nav' => 'Profil',
  'account_label_newpassword' => 'Neues Kennwort',
  'account_label_repeatedpassword' => 'Wiederholung',
  'account_legend' => '',
  'account_logout_nav' => 'Abmelden',
  'account_submit' => 'Aktualisieren',
  'account_submit_changepassword' => 'Kennwort ändern',
  'action_add' => 'Hinzufügen',
  'action_add_nav' => 'Hinzufügen',
  'action_add_select' => 'Sichern und mehr hinzufügen',
  'action_copy_nav' => 'Kopieren',
  'action_edit' => 'Ändern',
  'action_edit_select' => 'Sichern und bearbeiten',
  'action_expunge' => 'Entfernen',
  'action_expunge_select' => 'Löschen',
  'action_h1' => 'Aktionen',
  'action_idle_select' => 'Auf alle markierten&hellip;',
  'action_index' => 'Listen',
  'action_index_select' => 'Sichern und auflisten',
  'action_label_name' => 'Bezeichnung',
  'action_legend' => '',
  'action_list_nav' => 'Liste',
  'action_next_edit_select' => 'Sichern und nächsten bearbeiten',
  'action_prev_edit_select' => 'Sichern und vorigen bearbeiten',
  'action_read' => 'Anzeigen',
  'action_toggleArchived_select' => 'Archivierung wechseln',
  'action_toggleEnabled_select' => 'Aktivierung wechseln',
  'action_toggleInvisible_select' => 'Unsichtbarkeit wechseln',
  'action_toggleOnline_select' => 'Online Status wechseln',
  'address_country_select' => 'Wählen&hellip;',
  'address_label_billing' => 'Rechnung',
  'address_label_city' => 'Stadt',
  'address_label_country' => 'Land',
  'address_label_county' => 'Bundesland',
  'address_label_default' => 'Standard',
  'address_label_delivery' => 'Lieferung',
  'address_label_label' => 'Adressart',
  'address_label_other' => 'Sonstige',
  'address_label_private' => 'Privat',
  'address_label_select' => 'Art auswählen&hellip;',
  'address_label_street' => 'Strasse',
  'address_label_zip' => 'Postleitzahl',
  'admin_h1' => 'Einstellungen',
  'admin_head_title' => 'Einstellungen',
  'admin_submit_setting' => 'Aktualisieren',
  'app_claim' => 'RAD with Cinnebar, Redbean and Flight',
  'app_info' => '<a href="https://github.com/sah-comp/bienlein">Code on Github</a> - <a href="http://glyphicons.com/">Glyphicons</a>',
  'app_install_success' => 'Das Grundsystem ist erfolgreich installiert',
  'app_name' => 'Cinnebar',
  'bool_false' => 'Nein',
  'bool_true' => 'Ja',
  'browser_is_ancient' => 'Ihr Browser ist alt',
  'browser_is_not_supporting_iframe' => 'Die Vorschau konnte nicht eingebettet werden. Öffnen Sie die "Vorschau manuell":%s',
  'cms_add_page' => 'Fügen Sie eine neue Seite hinzu',
  'cms_addpage_w_template' => 'Neue Seite mit Template&hellip;',
  'cms_choose_a_node' => 'Wählen Sie einen Ordner aus',
  'cms_h1' => 'CMS',
  'cms_sitemap_nav' => 'Verzeichnis',
  'cms_url_has_no_pages' => 'Die URL %s hat keine Inhalte',
  'cms_url_not_found' => 'Die URL %s konnte nicht gefunden werden',
  'country_h1' => 'Länder',
  'country_label_enabled' => 'Aktiviert',
  'country_label_iso' => 'ISO',
  'country_label_name' => 'Name',
  'country_legend' => '',
  'country_translation_tab' => 'Übersetzungen',
  'currency_h1' => 'Währungen',
  'currency_info_basecurrency' => 'entspricht 1 %s',
  'currency_label_enabled' => 'Aktiviert',
  'currency_label_exchangerate' => 'Wechselkurs',
  'currency_label_fractionalunit' => 'Kleinste Einheit',
  'currency_label_iso' => 'ISO',
  'currency_label_name' => 'Name',
  'currency_label_numbertobasic' => 'Basiszahl',
  'currency_label_sign' => 'Zeichen',
  'currency_legend' => '',
  'domain_action' => 'Aktion',
  'domain_action_nav' => 'Aktionen',
  'domain_admin_nav' => 'Einstellungen',
  'domain_country' => 'Land',
  'domain_country_nav' => 'Länder',
  'domain_domain' => 'Verzeichnis',
  'domain_domain_nav' => 'Verzeichnisse',
  'domain_h1' => 'Verzeichnisse',
  'domain_label_action' => 'Kommando',
  'domain_label_i18n_name' => 'Verzeichnis',
  'domain_label_invisible' => 'Unsichtbar',
  'domain_label_name' => 'Bezeichnung',
  'domain_label_parent' => 'Übergeordnet',
  'domain_label_sequence' => 'Reihenfolge',
  'domain_label_url' => 'URL',
  'domain_language' => 'Sprache',
  'domain_language_nav' => 'Sprachen',
  'domain_legend' => '',
  'domain_legend_rbac' => 'Zugriffskontrolle',
  'domain_parent_none' => 'Ohne',
  'domain_preview_tab' => 'Vorschau',
  'domain_rbac_tab' => 'Zugriffsrechte',
  'domain_role' => 'Benutzerrolle',
  'domain_role_nav' => 'Benutzerrollen',
  'domain_team' => 'Team',
  'domain_team_nav' => 'Teams',
  'domain_token' => 'Token',
  'domain_token_nav' => 'Übersetzungen',
  'domain_translation_tab' => 'Übersetzungen',
  'domain_user' => 'Benutzer',
  'domain_user_nav' => 'Benutzerkonten',
  'email_h1' => 'Mailingadressen',
  'email_label_email' => 'E-Mail',
  'email_legend' => '',
  'email_legend_personkind' => '',
  'filter_placeholder_any' => 'Alle',
  'filter_submit_clear' => 'Filter zurücksetzen',
  'filter_submit_refresh' => 'Filter aktualisieren',
  'forbidden_head_title' => 'Zugriff nicht erlaubt',
  'http_error_403_article' => 'Wenden Sie sich an den Systemverwalter um Zugriff auf diese Seite zu erhalten.',
  'http_error_403_h1' => 'Fehler 403',
  'http_error_403_h2' => 'Zugriff nicht erlaubt',
  'http_error_404_article' => 'Die Seite konnte nicht gefunden werden.',
  'http_error_404_h1' => 'Fehler 404',
  'http_error_404_h2' => 'Seite nicht gefunden',
  'language_de' => 'Deutsch',
  'language_en' => 'Englisch',
  'language_h1' => 'Sprachen',
  'language_label_enabled' => 'Aktiviert',
  'language_label_iso' => 'ISO',
  'language_label_name' => 'Bezeichnung',
  'language_legend' => '',
  'language_us' => 'US Englisch',
  'login_failed' => 'Die Anmeldung ist fehlgeschlagen. Versuchen Sie es erneut',
  'login_h1' => 'Anmeldung',
  'login_head_title' => 'Anmeldung',
  'login_label_password' => 'Kennwort',
  'login_label_username' => 'Konto',
  'login_legend' => '',
  'login_link_lostpassword' => 'Neues Kennwort anfordern',
  'login_pw_wrong' => 'Das Kennwort ist falsch',
  'login_submit' => 'Anmelden',
  'login_user_not_found' => 'Der Benutzer ist unbekannt',
  'lorem_ipsum' => 'bq. In diesem Template wird _Lorem Ipsum_ ausgegeben. Generiert wird das HTML mit "Textile":http://redcloth.org/hobix.com/textile/

h1. Headline Level 1

You %{color:red}told me% to do this.

h2. Headline Level 2

Lorem ipsum[1] dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.

!/upload/placeholder.png(Beispielbild)!

h3. Headline Level 3

In enim justo, rhoncus ut, imperdiet a, *venenatis vitae*, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.

* We enjoy Textile
* for Lists
* and other _strict_ HTML stuff

# Erste Legion
# Zweite Kohorte
# Drittens Manipel

h3. Headline Level 3

Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem _quam semper libero_, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc

h3. Alignments

p>. Right aligned text is possible. Wow.

p=. This is a real stretch. Yes, a real stretch.

h3. Tables

| | Montag | Dienstag |
| 9 Uhr | 18°C | 15°C |
| 10 Uhr | 18°C | 15°C |
| 11 Uhr | 23°C | 17°C |
| 12 Uhr | 25°C | 20°C |

 <hr />

fn1. Fußnoten sind auch möglich.',
  'lostpassword_email_failed' => 'Die E-Mail mit einem neuen Kennwort konnte nicht versandt werden',
  'lostpassword_h1' => 'Neues Kennwort anfordern',
  'lostpassword_head_title' => 'Neues Kennwort anfordern',
  'lostpassword_label_username' => 'E-Mail',
  'lostpassword_legend' => '',
  'lostpassword_link_login' => 'Mein Kennwort ist mir wieder eingefallen',
  'lostpassword_notification_error' => 'lostpassword_notification_error',
  'lostpassword_submit' => 'Kennwort anfordern',
  'lostpassword_user_unknown' => 'Benutzer unbekannt. Verwenden Sie die E-Mail Adresse mit der Sie registriert sind',
  'mail_info_command' => 'Das Template wird mit Daten gemischt und dann an die oben eingetragene E-Mail zu Testzwecken versandt. Prüfen Sie Ihren Posteingang, schauen Sie auch in den <em>Spam-Ordner</em> und bewerten Sie ob der Newsletter tatsächlich versandtauglich ist.',
  'mail_info_template' => 'Das gewählte Template wird verwendet, um Ihren Newsletter zu generieren. Verwalten Sie <a href="/cms/template">Templates</a> und wählen Sie das gewünschte dann hier für den Newsletter aus.',
  'mailserver_h1' => 'Mailserver',
  'mailserver_info_name' => 'Tragen Sie in dieses Feld den Namen des Mailservers ein. Lassen Sie die restlichen Felder <em>leer</em> und verwenden Sie einen solchen Mailserver, um den Newsletter mittels des lokalen Mailer-Daemons zu versenden.',
  'mailserver_label_host' => 'Hostname',
  'mailserver_label_name' => 'Name',
  'mailserver_label_port' => 'Port',
  'mailserver_label_pw' => 'Kennwort',
  'mailserver_label_user' => 'Benutzer',
  'mailserver_legend' => '',
  'media_h1' => 'Medien',
  'media_label_desc' => 'Beschreibung',
  'media_label_extension' => 'Art',
  'media_label_file' => 'Datei',
  'media_label_name' => 'Name',
  'media_label_sanename' => 'Datei',
  'media_label_size' => 'Größe in Bytes',
  'media_legend' => '',
  'module_backend_info' => 'PHP Quellcode für die Verarbeitung im Eingabemodus',
  'module_backend_label' => 'Quellcode',
  'module_backend_tab' => 'Eingabe',
  'module_demo' => 'Demo für ein selbstentwickeltes Modul',
  'module_demo_output' => 'h2. Ein eigenes Module entwickeln

Rufen Sie "cms/module":/cms/module auf und erstellen Sie ein neues Modul auf der Basis des *Demo* Moduls.',
  'module_frontend_info' => 'PHP Quellcode für die Verarbeitung im Ausgabemodus',
  'module_frontend_label' => 'Quellcode',
  'module_frontend_tab' => 'Ausgabe',
  'module_gallery' => 'Galerie',
  'module_gallery_missing_content' => 'Leere Galerie',
  'module_h1' => 'Modulen',
  'module_html' => 'HTML',
  'module_html_missing_content' => 'Fehlendes HTML',
  'module_html_placeholder_content' => '<div class="custom">Hallo Welt</div>',
  'module_image' => 'Bild',
  'module_image_missing_media' => 'Fehlendes oder nicht ausgewähltes Bild',
  'module_image_placeholder_content' => 'Beschreiben Sie das Bild',
  'module_label_enabled' => 'Aktiviert',
  'module_label_name' => 'Name',
  'module_legend' => '',
  'module_legend_backend' => '',
  'module_legend_frontend' => '',
  'module_legend_html' => '',
  'module_legend_image' => '',
  'module_legend_text' => '',
  'module_legend_textile' => '',
  'module_submit' => 'Aktualisieren',
  'module_submit_choose' => 'Hinzufügen',
  'module_submit_delete' => 'Entfernen',
  'module_text' => 'Nur-Text',
  'module_text_missing_content' => 'Ohne Text',
  'module_text_placeholder_content' => 'Lorem ipsum',
  'module_textile' => 'Textile',
  'module_textile_missing_content' => 'Leeres Textile',
  'module_textile_placeholder_content' => 'h1. Überschrift',
  'module_your_code_here' => 'h2. Programm-Code für das Module hier',
  'news_h1' => 'Nachrichten',
  'news_info_content' => 'Verwenden Sie Textile',
  'news_info_teaser' => 'Verwenden Sie Textile',
  'news_label_archived' => 'Archiviert',
  'news_label_content' => 'Inhalt',
  'news_label_name' => 'Überschrift',
  'news_label_newscat' => 'Kategorie',
  'news_label_newscat_id' => 'Kategorie',
  'news_label_online' => 'Publiziert',
  'news_label_pubdatetime' => 'Datum und Zeit',
  'news_label_teaser' => 'Teaser',
  'news_legend' => '',
  'newscat_h1' => 'Kategorien',
  'newscat_label_name' => 'Name',
  'newscat_legend' => '',
  'newscat_translation_tab' => 'Übersetzungen',
  'newsletter_command_idle' => 'Leerlauf',
  'newsletter_command_make' => 'Zum Versand vorbereiten',
  'newsletter_command_please_select' => 'Auswählen&hellip;',
  'newsletter_command_test' => 'Testen',
  'newsletter_h1' => 'Newsletter',
  'newsletter_label_command' => 'Kommando',
  'newsletter_label_mailserver' => 'Mailserver',
  'newsletter_label_mailserver_name' => 'Mailserver',
  'newsletter_label_name' => 'Name',
  'newsletter_label_replytoemail' => 'Antwort Mailadresse',
  'newsletter_label_replytoname' => 'Absendername',
  'newsletter_label_template' => 'Template',
  'newsletter_label_template_name' => 'Template',
  'newsletter_label_testemail' => 'Test E-Mailadresse',
  'newsletter_mailserver_please_select' => 'Auswählen&hellip;',
  'newsletter_template_please_select' => 'Auswählen&hellip;',
  'newsletter_test_failed' => 'Testversand ist fehlgeschlagen. Prüfen Sie die Daten des Mailservers und versuchen Sie es erneut.',
  'notfound_head_title' => 'Seite nicht gefunden',
  'page_domain_none' => 'Ohne',
  'page_h1' => 'Webseiten',
  'page_label_desc' => 'Beschreibung',
  'page_label_domain' => 'Verzeichnis',
  'page_label_invisible' => 'Nicht sichtbar',
  'page_label_keywords' => 'Suchbegriffe',
  'page_label_name' => 'Titel',
  'page_label_sequence' => 'Reihenfolge',
  'page_label_template' => 'Template',
  'page_label_url' => 'URL',
  'page_legend' => '',
  'page_legend_meta' => '',
  'page_legend_region' => '',
  'page_meta_tab' => 'Meta',
  'page_name_untitled' => 'Unbenannt',
  'page_region_tab' => 'Bereiche',
  'page_submit' => 'Aktualisieren',
  'page_submit_delete' => 'Entfernen',
  'page_template_none' => 'Ohne',
  'pagination_page_next' => 'Nächste',
  'pagination_page_prev' => 'Vorige',
  'person_address_tab' => 'Postanschriften',
  'person_h1' => 'Adressbuch',
  'person_label_account' => 'Konto',
  'person_label_attention' => 'Anrede',
  'person_label_company' => 'Firma',
  'person_label_department' => 'Abteilung',
  'person_label_email' => 'E-Mail',
  'person_label_enabled' => 'Aktiv',
  'person_label_fax' => 'Fax',
  'person_label_firstname' => 'Vorname',
  'person_label_jobtitle' => 'Position',
  'person_label_language' => 'Sprache',
  'person_label_lastname' => 'Nachname',
  'person_label_name' => 'Name',
  'person_label_nickname' => 'Kurzname',
  'person_label_organization' => 'Organisation',
  'person_label_phone' => 'Telefon',
  'person_label_suffix' => 'Zusatz',
  'person_label_title' => 'Titel',
  'person_label_url' => 'Webseite',
  'person_label_vatid' => 'Umsatzsteuer Id',
  'person_legend' => '',
  'person_legend_address' => '',
  'person_legend_email' => '',
  'person_legend_name' => '',
  'person_legend_organization' => '',
  'person_legend_phone' => '',
  'person_placeholder_nickname' => 'Eindeutiger Name',
  'person_role_tab' => 'Rollen',
  'personkind_h1' => 'Gruppen',
  'personkind_label_name' => 'Name',
  'personkind_legend' => '',
  'region_label_name' => '%d Bereich',
  'region_legend' => '',
  'role_h1' => 'Benutzerrollen',
  'role_label_name' => 'Bezeichnung',
  'role_legend' => '',
  'role_translation_tab' => 'Übersetzungen',
  'scaffold_action_edit' => 'Bearbeiten',
  'scaffold_attach' => 'Hinzufügen',
  'scaffold_attach_linktext' => 'Hinzufügen',
  'scaffold_caption_index' => '%d Einträge',
  'scaffold_detach' => 'Entfernen',
  'scaffold_detach_linktext' => 'Entfernen',
  'scaffold_dup_goto_original' => 'Kopie bearbeiten und sichern oder das "Original bearbeiten":%s',
  'scaffold_error_add' => 'Der Eintrag konnte nicht hinzugefügt werden',
  'scaffold_error_edit' => 'Der Eintrag konnte nicht geändert werden',
  'scaffold_error_index' => 'Die Aktion konnte nicht auf die Auswahl angewandt werden',
  'scaffold_head_title_add' => 'Einen neuen Eintrag hinzufügen',
  'scaffold_head_title_edit' => 'Bearbeiten eines Eintrages',
  'scaffold_head_title_index' => 'Blättern',
  'scaffold_inline_please_select' => 'Auswählen&hellip;',
  'scaffold_no_records_add_denied' => 'Es sind keine Einträge vorhanden',
  'scaffold_no_records_add_one' => 'Es sind noch keine Einträge vorhanden. Erstellen Sie den ersten',
  'scaffold_select_all' => 'Markierung für alle setzen oder aufheben',
  'scaffold_submit_apply_action' => 'Anwenden',
  'scaffold_success_add' => 'Ein Eintrag wurde erfolgreich hinzugefügt',
  'scaffold_success_edit' => 'Der Eintrag wurde geändert',
  'scaffold_success_index' => 'Die Aktion wurde auf %d Einträge angewandt',
  'setting_currency_tab' => 'Währung und Kurse',
  'setting_folder_tab' => 'Ordner',
  'setting_homepage_info' => 'Ohne Startseite erscheint die Standard Willkommen-Seite',
  'setting_homepage_none' => 'Ohne',
  'setting_label_basecurrency' => 'Basiswährung',
  'setting_label_blessedfolder' => 'Systemordner',
  'setting_label_exchangerateservice' => 'Service',
  'setting_label_fiscalyear' => 'Rechnungsjahr',
  'setting_label_homepage' => 'Startseite',
  'setting_label_loadexchangerates' => 'Kurse',
  'setting_label_sitesfolder' => 'Webseiten',
  'setting_legend' => '',
  'setting_legend_currency' => '',
  'setting_legend_folder' => '',
  'setting_loadexchangerates_no' => 'Zuletzt aktualisiert %s',
  'setting_loadexchangerates_yes' => 'Jetzt aktualisieren',
  'slice_label_class' => 'Klasse',
  'slice_label_css' => 'Stilangaben',
  'slice_label_tag' => 'Tag',
  'slice_media_select' => 'Medium&hellip;',
  'slice_module_not_set' => '&hellip; um Inhalte einzutragen',
  'slice_module_select' => 'Modul wählen&hellip;',
  'slice_placeholder_class' => 'Optionale Angabe einer CSS Klasse',
  'slice_placeholder_css' => 'Optionale CSS Stilangaben',
  'slice_placeholder_tag' => 'Optional umschließender HTML Tag',
  'sys_info' => '%dMB &dash; IP: %s  &dash; %d Abfragen',
  'team_h1' => 'Teams',
  'team_label_name' => 'Bezeichnung',
  'team_legend' => '',
  'team_translation_tab' => 'Übersetzungen',
  'template_h1' => 'Templates',
  'template_html_info' => 'HTML wird mit Inhalten aus dem CMS gemischt',
  'template_html_tab' => 'HTML',
  'template_label_html' => 'HTML',
  'template_label_name' => 'Name',
  'template_label_text' => 'Nur-Text',
  'template_legend' => '',
  'template_legend_html' => '',
  'template_legend_region' => '',
  'template_legend_text' => 'Nur-Text',
  'template_region_tab' => 'Bereiche',
  'template_text_info' => 'Nur-Text wird z.B. bei E-Mail Versand benutzt',
  'template_text_tab' => 'Nur-Text',
  'token_h1' => 'Übersetzungen',
  'token_info_desc' => 'Beschreibung des Token mit eventuellen Parametern',
  'token_label_desc' => 'Beschreibung',
  'token_label_i18n_name' => 'Übersetzung',
  'token_label_name' => 'Mnemonik',
  'token_legend' => '',
  'token_placeholder_desc' => 'Beschreibung eventueller Ersetzungsparameter und Verwendungszweck',
  'token_translation_tab' => 'Übersetzungen',
  'tokeni18n_legend' => '',
  'user_editor_tab' => 'Listen und Formulare',
  'user_h1' => 'Benutzerkonten',
  'user_info_maxlifetime' => 'Anzahl der Sekunden bis eine Sitzung beendet wird',
  'user_info_recordsperpage' => 'Wählen Sie eine geringere Zahl um die Seiten schneller darzustellen und eine größere Zahl um weniger blättern zu müssen.',
  'user_label_allrecordsperpage' => 'Zeige alle Datensätze in der Listenansicht...',
  'user_label_email' => 'E-Mail',
  'user_label_foxylisteditor' => 'Direktes Bearbeiten in der Listenansicht',
  'user_label_isadmin' => 'Darf das System verwalten',
  'user_label_isbanned' => 'Konto ist zur Zeit gesperrt',
  'user_label_isdeleted' => 'Konto zur Löschung vorgesehen',
  'user_label_maxlifetime' => 'Sitzungsdauer',
  'user_label_name' => 'Name',
  'user_label_pw' => 'Kennwort',
  'user_label_recordsperpage' => '... oder zeige Datensätze je Seite',
  'user_label_screenname' => 'Profilname',
  'user_label_shortname' => 'Kurzname',
  'user_legend' => '',
  'user_legend_role' => '',
  'user_legend_setting' => '',
  'user_legend_team' => '',
  'user_role_tab' => 'Rollen',
  'user_setting_tab' => 'Einstellungen',
  'user_team_tab' => 'Teams',
  'validator_hasvalue_invalid' => 'fehlende Angabe',
  'validator_isdate_invalid' => 'ist ein fehlerhaftes Datum',
  'validator_isemail_invalid' => 'ist keine als gültig erkannte E-Mail Adresse',
  'validator_isnumeric_invalid' => 'ist keine Zahl',
  'validator_isunique_invalid' => 'ist bereits vorhanden',
  'validator_range_invalid' => 'liegt ausserhalb des gültigen Bereiches',
  'welcome_head_title' => 'Willkommen - Diese Seite ist absichtlich leer',
);
